create table if not exists public.shadow_evaluations (
  id bigint generated by default as identity primary key,
  candidate_key text not null,
  alert_id text,
  ref_id text,
  symbol text,
  direction text,
  timeframe text,
  setup_type text,
  live_decision text not null default 'ACCEPTED',
  shadow_version text not null,
  event_time_utc timestamptz,
  evaluated_at_utc timestamptz not null default now(),
  outcome_type text,
  outcome_time_utc timestamptz,
  move_pct double precision,
  r_multiple double precision,
  raw_context jsonb,
  unique(candidate_key, shadow_version)
);

create table if not exists public.shadow_rule_results (
  id bigint generated by default as identity primary key,
  candidate_key text not null,
  alert_id text,
  ref_id text,
  rule_name text not null,
  rule_status text not null,
  score_adjustment integer not null default 0,
  would_reject boolean not null default false,
  reason text,
  details jsonb,
  shadow_version text not null,
  evaluated_at_utc timestamptz not null default now(),
  outcome_type text,
  outcome_time_utc timestamptz,
  move_pct double precision,
  r_multiple double precision,
  rejection_would_help boolean,
  rejection_would_hurt boolean,
  unique(candidate_key, shadow_version, rule_name)
);

create table if not exists public.shadow_combo_results (
  id bigint generated by default as identity primary key,
  candidate_key text not null,
  alert_id text,
  ref_id text,
  combo_name text not null,
  rule_names text[] not null,
  combo_status text not null,
  total_score_adjustment integer not null default 0,
  would_reject boolean not null default false,
  reasons text[],
  details jsonb,
  shadow_version text not null,
  evaluated_at_utc timestamptz not null default now(),
  outcome_type text,
  outcome_time_utc timestamptz,
  move_pct double precision,
  r_multiple double precision,
  rejection_would_help boolean,
  rejection_would_hurt boolean,
  unique(candidate_key, shadow_version, combo_name)
);

create table if not exists public.shadow_optimizer_reports (
  id bigint generated by default as identity primary key,
  report_key text not null unique,
  report_type text not null,
  shadow_version text not null,
  period_start_utc timestamptz,
  period_end_utc timestamptz,
  generated_at_utc timestamptz not null default now(),
  summary jsonb not null default '{}'::jsonb,
  recommendations jsonb not null default '[]'::jsonb
);

create index if not exists shadow_evaluations_candidate_idx on public.shadow_evaluations(candidate_key);
create index if not exists shadow_evaluations_alert_idx on public.shadow_evaluations(alert_id);
create index if not exists shadow_evaluations_symbol_idx on public.shadow_evaluations(symbol);
create index if not exists shadow_evaluations_event_time_idx on public.shadow_evaluations(event_time_utc);
create index if not exists shadow_evaluations_outcome_idx on public.shadow_evaluations(outcome_type);

create index if not exists shadow_rule_results_candidate_idx on public.shadow_rule_results(candidate_key);
create index if not exists shadow_rule_results_rule_idx on public.shadow_rule_results(rule_name);
create index if not exists shadow_rule_results_status_idx on public.shadow_rule_results(rule_status);
create index if not exists shadow_rule_results_reject_idx on public.shadow_rule_results(would_reject);
create index if not exists shadow_rule_results_outcome_idx on public.shadow_rule_results(outcome_type);

create index if not exists shadow_combo_results_candidate_idx on public.shadow_combo_results(candidate_key);
create index if not exists shadow_combo_results_combo_idx on public.shadow_combo_results(combo_name);
create index if not exists shadow_combo_results_reject_idx on public.shadow_combo_results(would_reject);
create index if not exists shadow_combo_results_outcome_idx on public.shadow_combo_results(outcome_type);

create or replace view public.shadow_rule_scoreboard as
select
  rule_name as improvement_name,
  shadow_version,
  count(*) as evaluated_alerts,
  count(*) filter (where would_reject) as flagged_alerts,
  count(*) filter (where would_reject and outcome_type in ('SL', 'TIME_EXIT_LOSS')) as losses_avoided,
  count(*) filter (where would_reject and outcome_type in ('TP', 'TP1', 'TP2', 'TP_FULL', 'TIME_EXIT_PROFIT')) as wins_lost,
  avg(move_pct) filter (where outcome_type is not null) as avg_move_pct,
  avg(r_multiple) filter (where r_multiple is not null) as avg_r_multiple,
  case
    when count(*) filter (where would_reject and outcome_type is not null) = 0 then null
    else
      count(*) filter (where would_reject and outcome_type in ('SL', 'TIME_EXIT_LOSS'))::double precision
      / nullif(count(*) filter (where would_reject and outcome_type is not null), 0)
  end as flagged_loss_rate
from public.shadow_rule_results
group by rule_name, shadow_version;

create or replace view public.shadow_combo_scoreboard as
select
  combo_name as improvement_name,
  shadow_version,
  count(*) as evaluated_alerts,
  count(*) filter (where would_reject) as flagged_alerts,
  count(*) filter (where would_reject and outcome_type in ('SL', 'TIME_EXIT_LOSS')) as losses_avoided,
  count(*) filter (where would_reject and outcome_type in ('TP', 'TP1', 'TP2', 'TP_FULL', 'TIME_EXIT_PROFIT')) as wins_lost,
  avg(move_pct) filter (where outcome_type is not null) as avg_move_pct,
  avg(r_multiple) filter (where r_multiple is not null) as avg_r_multiple,
  case
    when count(*) filter (where would_reject and outcome_type is not null) = 0 then null
    else
      count(*) filter (where would_reject and outcome_type in ('SL', 'TIME_EXIT_LOSS'))::double precision
      / nullif(count(*) filter (where would_reject and outcome_type is not null), 0)
  end as flagged_loss_rate
from public.shadow_combo_results
group by combo_name, shadow_version;
