create table if not exists public.optimizer_rule_snapshots (
  id bigint generated by default as identity primary key,
  snapshot_key text not null unique,
  period_type text not null,
  period_start_utc timestamptz,
  period_end_utc timestamptz,
  shadow_version text not null,
  rule_name text not null,
  evaluated_alerts integer not null default 0,
  flagged_alerts integer not null default 0,
  passed_alerts integer not null default 0,
  closed_outcomes integer not null default 0,
  open_trades integer not null default 0,
  tp_count integer not null default 0,
  sl_count integer not null default 0,
  time_exit_profit_count integer not null default 0,
  time_exit_loss_count integer not null default 0,
  expired_count integer not null default 0,
  losses_avoided integer not null default 0,
  wins_missed integer not null default 0,
  net_value double precision,
  baseline_winrate double precision,
  simulated_winrate double precision,
  winrate_delta double precision,
  baseline_expectancy double precision,
  simulated_expectancy double precision,
  expectancy_delta double precision,
  avg_r_multiple double precision,
  confidence_level text not null,
  confidence_score integer not null default 0,
  recommendation_status text not null,
  generated_at_utc timestamptz not null default now()
);

create table if not exists public.optimizer_combo_snapshots (
  id bigint generated by default as identity primary key,
  snapshot_key text not null unique,
  period_type text not null,
  period_start_utc timestamptz,
  period_end_utc timestamptz,
  shadow_version text not null,
  combo_name text not null,
  rule_names text[] not null default '{}',
  evaluated_alerts integer not null default 0,
  flagged_alerts integer not null default 0,
  passed_alerts integer not null default 0,
  closed_outcomes integer not null default 0,
  open_trades integer not null default 0,
  tp_count integer not null default 0,
  sl_count integer not null default 0,
  time_exit_profit_count integer not null default 0,
  time_exit_loss_count integer not null default 0,
  expired_count integer not null default 0,
  losses_avoided integer not null default 0,
  wins_missed integer not null default 0,
  net_value double precision,
  baseline_winrate double precision,
  simulated_winrate double precision,
  winrate_delta double precision,
  baseline_expectancy double precision,
  simulated_expectancy double precision,
  expectancy_delta double precision,
  avg_r_multiple double precision,
  confidence_level text not null,
  confidence_score integer not null default 0,
  recommendation_status text not null,
  generated_at_utc timestamptz not null default now()
);

create table if not exists public.optimizer_recommendations (
  id bigint generated by default as identity primary key,
  recommendation_key text not null unique,
  period_type text not null,
  period_start_utc timestamptz,
  period_end_utc timestamptz,
  shadow_version text not null,
  subject_type text not null,
  subject_name text not null,
  rank integer,
  sample_size integer not null default 0,
  confidence_level text not null,
  confidence_score integer not null default 0,
  status text not null,
  estimated_impact double precision,
  evidence jsonb not null default '{}'::jsonb,
  recommendation text not null,
  generated_at_utc timestamptz not null default now()
);

create index if not exists optimizer_rule_snapshots_period_idx on public.optimizer_rule_snapshots(period_type, period_start_utc, period_end_utc);
create index if not exists optimizer_rule_snapshots_rule_idx on public.optimizer_rule_snapshots(rule_name);
create index if not exists optimizer_rule_snapshots_confidence_idx on public.optimizer_rule_snapshots(confidence_level);

create index if not exists optimizer_combo_snapshots_period_idx on public.optimizer_combo_snapshots(period_type, period_start_utc, period_end_utc);
create index if not exists optimizer_combo_snapshots_combo_idx on public.optimizer_combo_snapshots(combo_name);
create index if not exists optimizer_combo_snapshots_confidence_idx on public.optimizer_combo_snapshots(confidence_level);

create index if not exists optimizer_recommendations_period_idx on public.optimizer_recommendations(period_type, period_start_utc, period_end_utc);
create index if not exists optimizer_recommendations_subject_idx on public.optimizer_recommendations(subject_type, subject_name);
create index if not exists optimizer_recommendations_status_idx on public.optimizer_recommendations(status);

create or replace view public.optimizer_latest_rule_leaderboard as
select *
from public.optimizer_rule_snapshots
where generated_at_utc = (
  select max(generated_at_utc)
  from public.optimizer_rule_snapshots
);

create or replace view public.optimizer_latest_combo_leaderboard as
select *
from public.optimizer_combo_snapshots
where generated_at_utc = (
  select max(generated_at_utc)
  from public.optimizer_combo_snapshots
);

create or replace view public.optimizer_latest_recommendations as
select *
from public.optimizer_recommendations
where generated_at_utc = (
  select max(generated_at_utc)
  from public.optimizer_recommendations
);
