alter table public.optimizer_rule_snapshots
  add column if not exists observation_days integer not null default 0,
  add column if not exists stability_score integer not null default 0;

alter table public.optimizer_combo_snapshots
  add column if not exists observation_days integer not null default 0,
  add column if not exists stability_score integer not null default 0;

create table if not exists public.optimizer_monitoring_reports (
  id bigint generated by default as identity primary key,
  report_key text not null unique,
  report_type text not null,
  period_type text not null,
  period_start_utc timestamptz,
  period_end_utc timestamptz,
  generated_at_utc timestamptz not null default now(),
  summary jsonb not null default '{}'::jsonb,
  top_rules jsonb not null default '[]'::jsonb,
  top_combos jsonb not null default '[]'::jsonb,
  fastest_improving jsonb not null default '[]'::jsonb,
  fastest_declining jsonb not null default '[]'::jsonb,
  highest_confidence jsonb not null default '[]'::jsonb,
  largest_sample jsonb not null default '[]'::jsonb
);

create index if not exists optimizer_monitoring_reports_type_idx
  on public.optimizer_monitoring_reports(report_type, period_type, generated_at_utc);

create or replace view public.optimizer_rule_trends as
select
  r.*,
  r.net_value - lag(r.net_value) over (
    partition by r.period_type, r.shadow_version, r.rule_name
    order by r.generated_at_utc
  ) as net_value_change,
  r.expectancy_delta - lag(r.expectancy_delta) over (
    partition by r.period_type, r.shadow_version, r.rule_name
    order by r.generated_at_utc
  ) as expectancy_delta_change,
  r.closed_outcomes - lag(r.closed_outcomes) over (
    partition by r.period_type, r.shadow_version, r.rule_name
    order by r.generated_at_utc
  ) as sample_growth,
  r.confidence_score - lag(r.confidence_score) over (
    partition by r.period_type, r.shadow_version, r.rule_name
    order by r.generated_at_utc
  ) as confidence_score_change
from public.optimizer_rule_snapshots r;

create or replace view public.optimizer_combo_trends as
select
  c.*,
  c.net_value - lag(c.net_value) over (
    partition by c.period_type, c.shadow_version, c.combo_name
    order by c.generated_at_utc
  ) as net_value_change,
  c.expectancy_delta - lag(c.expectancy_delta) over (
    partition by c.period_type, c.shadow_version, c.combo_name
    order by c.generated_at_utc
  ) as expectancy_delta_change,
  c.closed_outcomes - lag(c.closed_outcomes) over (
    partition by c.period_type, c.shadow_version, c.combo_name
    order by c.generated_at_utc
  ) as sample_growth,
  c.confidence_score - lag(c.confidence_score) over (
    partition by c.period_type, c.shadow_version, c.combo_name
    order by c.generated_at_utc
  ) as confidence_score_change
from public.optimizer_combo_snapshots c;

create or replace view public.optimizer_admin_top_rules as
select
  rule_name as subject_name,
  'rule'::text as subject_type,
  period_type,
  closed_outcomes as sample_size,
  losses_avoided,
  wins_missed,
  net_value,
  expectancy_delta,
  confidence_level,
  confidence_score,
  recommendation_status,
  observation_days,
  stability_score,
  generated_at_utc
from public.optimizer_latest_rule_leaderboard
order by confidence_score desc, net_value desc nulls last, expectancy_delta desc nulls last;

create or replace view public.optimizer_admin_top_combos as
select
  combo_name as subject_name,
  'combo'::text as subject_type,
  period_type,
  closed_outcomes as sample_size,
  losses_avoided,
  wins_missed,
  net_value,
  expectancy_delta,
  confidence_level,
  confidence_score,
  recommendation_status,
  observation_days,
  stability_score,
  generated_at_utc
from public.optimizer_latest_combo_leaderboard
order by confidence_score desc, net_value desc nulls last, expectancy_delta desc nulls last;

create or replace view public.optimizer_admin_fastest_improving as
select
  rule_name as subject_name,
  'rule'::text as subject_type,
  period_type,
  closed_outcomes as sample_size,
  net_value_change,
  expectancy_delta_change,
  sample_growth,
  confidence_score_change,
  recommendation_status,
  generated_at_utc
from public.optimizer_rule_trends
where generated_at_utc = (select max(generated_at_utc) from public.optimizer_rule_snapshots)
union all
select
  combo_name as subject_name,
  'combo'::text as subject_type,
  period_type,
  closed_outcomes as sample_size,
  net_value_change,
  expectancy_delta_change,
  sample_growth,
  confidence_score_change,
  recommendation_status,
  generated_at_utc
from public.optimizer_combo_trends
where generated_at_utc = (select max(generated_at_utc) from public.optimizer_combo_snapshots)
order by net_value_change desc nulls last, expectancy_delta_change desc nulls last;

create or replace view public.optimizer_admin_fastest_declining as
select *
from public.optimizer_admin_fastest_improving
order by net_value_change asc nulls last, expectancy_delta_change asc nulls last;

create or replace view public.optimizer_admin_highest_confidence as
select
  subject_name,
  subject_type,
  period_type,
  sample_size,
  confidence_level,
  confidence_score,
  recommendation_status,
  observation_days,
  stability_score,
  generated_at_utc
from (
  select * from public.optimizer_admin_top_rules
  union all
  select * from public.optimizer_admin_top_combos
) x
order by confidence_score desc, sample_size desc;

create or replace view public.optimizer_admin_largest_sample as
select
  subject_name,
  subject_type,
  period_type,
  sample_size,
  confidence_level,
  confidence_score,
  recommendation_status,
  observation_days,
  stability_score,
  generated_at_utc
from (
  select * from public.optimizer_admin_top_rules
  union all
  select * from public.optimizer_admin_top_combos
) x
order by sample_size desc, confidence_score desc;
