create table if not exists public.shadow_score_evaluations (
  id bigint generated by default as identity primary key,
  candidate_key text not null,
  alert_id text,
  ref_id text,
  symbol text,
  direction text,
  timeframe text,
  setup_type text,
  live_decision text not null default 'PENDING',
  decision_reason text,
  shadow_version text not null,
  event_time_utc timestamptz,
  evaluated_at_utc timestamptz not null default now(),
  posted_to_paid boolean not null default false,
  posted_to_free boolean not null default false,

  current_score integer,
  current_grade text,
  proposed_score integer,
  proposed_grade text,
  score_delta integer,
  score_components jsonb not null default '{}'::jsonb,
  penalty_reasons jsonb not null default '[]'::jsonb,
  bonus_reasons jsonb not null default '[]'::jsonb,
  major_penalty_active boolean not null default false,
  recommended_action text,

  outcome_type text,
  outcome_time_utc timestamptz,
  market_move_pct double precision,
  r_multiple double precision,
  return_2x double precision,
  return_3x double precision,
  return_4x double precision,
  return_5x double precision,
  return_6x double precision,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  unique(candidate_key, shadow_version)
);

create index if not exists shadow_score_candidate_idx on public.shadow_score_evaluations(candidate_key);
create index if not exists shadow_score_alert_idx on public.shadow_score_evaluations(alert_id);
create index if not exists shadow_score_ref_idx on public.shadow_score_evaluations(ref_id);
create index if not exists shadow_score_event_time_idx on public.shadow_score_evaluations(event_time_utc);
create index if not exists shadow_score_current_grade_idx on public.shadow_score_evaluations(current_grade);
create index if not exists shadow_score_proposed_grade_idx on public.shadow_score_evaluations(proposed_grade);
create index if not exists shadow_score_outcome_idx on public.shadow_score_evaluations(outcome_type);
create index if not exists shadow_score_symbol_idx on public.shadow_score_evaluations(symbol);
create index if not exists shadow_score_setup_idx on public.shadow_score_evaluations(setup_type);

alter table public.alert_candidates
  add column if not exists score_components jsonb,
  add column if not exists current_score integer,
  add column if not exists current_grade text,
  add column if not exists proposed_score integer,
  add column if not exists proposed_grade text,
  add column if not exists score_delta integer;

create or replace view public.shadow_score_weekly_performance as
select
  date_trunc('week', event_time_utc)::date as week_start,
  shadow_version,
  proposed_grade,
  count(*) as alerts,
  count(*) filter (where outcome_type is not null) as closed,
  count(*) filter (where outcome_type in ('TP', 'TP1', 'TP2', 'TP_FULL', 'TIME_EXIT_PROFIT')) as wins,
  count(*) filter (where outcome_type in ('SL', 'TIME_EXIT_LOSS')) as losses,
  count(*) filter (where outcome_type in ('TP', 'TP1', 'TP2', 'TP_FULL')) as tp,
  count(*) filter (where outcome_type = 'SL') as sl,
  avg(market_move_pct) filter (where outcome_type is not null) as average_market_move_pct,
  avg(r_multiple) filter (where r_multiple is not null) as average_r_multiple,
  case
    when count(*) filter (where outcome_type is not null) = 0 then null
    else
      100.0 * count(*) filter (where outcome_type in ('TP', 'TP1', 'TP2', 'TP_FULL', 'TIME_EXIT_PROFIT'))
      / nullif(count(*) filter (where outcome_type is not null), 0)
  end as winrate_pct
from public.shadow_score_evaluations
group by date_trunc('week', event_time_utc)::date, shadow_version, proposed_grade;
